import type { Metadata } from "next";
import {  Darker_Grotesque, Lexend } from "next/font/google";
import "./globals.css";

// Available subsets: `latin`, `latin-ext`, `vietnamese`
const darkerGrotesque = Darker_Grotesque({
  subsets: ['latin'],
  display: 'swap',
  variable:'--font-darker'
});

const lexendFont = Lexend({
  subsets: ["latin"],
  display: 'swap',
  variable:'--font-lexend'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${darkerGrotesque.variable} ${lexendFont.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
