services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - .env

  # frontend:
  #   build:
  #     context: ./frontend
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost:8000/api
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - backend